### PR TITLE
Modified project to add .NET Core 3.0 support

### PR DESCRIPTION
**Pull request by progdogusmc**
Modified project to build .NET Core 3.0 and .NET Framework 4.5 compatible DLL.

### CODE REVIEW

**Comment by progdogusmc** [comment]
Commit message should read v141, my apologies. Still appears to support .NET Core 3.0 without issues.

**Comment by ssuluh** [comment]
Hey Kevin, I've looked at your PR great work figuring out the .net core 3.0. I'm still thinking how the best way to accomplish the integration of this PR
Here are couple things that we need to take care of:
1. I'm ok on the change but until we can get CI/CD working it's going to be tough to build release version. Our CI/CD is using AppVeyor, I haven't checked if they have a build agent that support .Net core 3.0 just yet. Also we may have to tweak the nuget package .nupkg itself. If your work require it right now, just go ahead make a private version and incorporate them in your project, and as soon as we get the pipeline running and publish to nuget.org correctly, you can refactor to use the official one. 

2. I saw your PR has a lot of intermediate commit. Part of my goal, master branch should be as clean as possible as far as git history is concerned, we want to always be vigilant about this from early on. So please squash things that is irrelevant for the PR. What I find helpful before working making code change on any OSS, I started with syncing my repo using rebase command. Don't just do merges, this will yield to non linear history. I think I may have a rule in the master to only allow fast forward, so unless it's linear github will reject PR during the merge process. During the commit if someone else push something in the upstream, I will rebase mine again with that and update my PR.
Great work man. Thank you for your contribution.
Regards,Surya
    On Saturday, November 30, 2019, 11:28:01 PM EST, Kevin M. Kelly <notifications@github.com> wrote:  
 
 
Commit message should read v141, my apologies. Still appears to support .NET Core 3.0 without issues.

**Comment by progdogusmc** [comment]
Okay, I will refork and recommit my changes to the fork then submit a new
pull request! My work doesn't require the .NET Core version yet, but I
tested it with a basic console application and it seems to work. Thanks
again for the opportunity to contribute.

--Kevin

**Comment by ssuluh** [comment]
Look at git rebase interactive etc. If u use git kraken or sourcetree u can tidy up your commit in the UI very easy.On Dec 2, 2019 12:12 AM, "Kevin M. Kelly" <notifications@github.com> wrote:Okay, I will refork and recommit my changes to the fork then submit a new

pull request! My work doesn't require the .NET Core version yet, but I

tested it with a basic console application and it seems to work. Thanks

again for the opportunity to contribute.



--Kevin

**Pull request closed without merging**
